import 'package:flutter/material.dart';

// 메인 파트너 세로 리스트

final List<Map<String, dynamic>> groupRankingData = [
  {
    'avaterImagePath':'main_sample_avater',
    'bgImagePath': 'main_sample05',
    'companyName': '청년 한다발 서초점',
    'userName': '김훈민',
    'tagList': ['#서초구', '#당일배달', '#꽃다발'],
    'ranking': '1',
    'money': '10000000',
  },
  {
    'avaterImagePath':'main_sample_avater2',
    'bgImagePath': 'main_sample06',
    'companyName': '골프여신 내동점',
    'userName': '임성택',
    'tagList': ['#사전예약', '#당일레슨', '#하우스'],
    'ranking': '2',
    'money': '10000',
  },
  {
    'avaterImagePath':'main_sample_avater3',
    'bgImagePath': 'main_sample07',
    'companyName': '헬스청년 괴정점',
    'userName': '이규봉',
    'tagList': ['#1:1', '#개인PT', '#신규환영'],
    'ranking': '3',
    'money': '10000',
  },
  {
    'avaterImagePath':'main_sample_avater2',
    'bgImagePath': 'main_sample08',
    'companyName': '청년 한다발 서초점',
    'userName': '홍길동',
    'tagList': ['#서초구', '#당일배달', '#꽃다발'],
    'ranking': '4',
    'money': '10000',
  },
  {
    'avaterImagePath':'main_sample_avater',
    'bgImagePath': 'main_sample09',
    'companyName': '청년 한다발 서초점',
    'userName': '홍길순',
    'tagList': ['#서초구', '#당일배달', '#꽃다발'],
    'ranking': '5',
    'money': '10000',
  },
  {
    'avaterImagePath':'main_sample_avater2',
    'bgImagePath': 'main_sample06',
    'companyName': '골프여신 내동점',
    'userName': '임성택',
    'tagList': ['#사전예약', '#당일레슨', '#하우스'],
    'ranking': '6',
    'money': '10000',
  },
  {
    'avaterImagePath':'main_sample_avater2',
    'bgImagePath': 'main_sample06',
    'companyName': '골프여신 내동점',
    'userName': '임성택',
    'tagList': ['#사전예약', '#당일레슨', '#하우스'],
    'ranking': '7',
    'money': '10000',
  },
  {
    'avaterImagePath':'main_sample_avater2',
    'bgImagePath': 'main_sample06',
    'companyName': '골프여신 내동점',
    'userName': '임성택',
    'tagList': ['#사전예약', '#당일레슨', '#하우스'],
    'ranking': '8',
    'money': '10000',
  },
  {
    'avaterImagePath':'main_sample_avater2',
    'bgImagePath': 'main_sample06',
    'companyName': '골프여신 내동점',
    'userName': '임성택',
    'tagList': ['#사전예약', '#당일레슨', '#하우스'],
    'ranking': '9',
    'money': '10000',
  },

];